add_library(OrderBook.Core
        #OrderBook.Core.cpp
        OrderBook.Core.h
        Order.h
        Order.cpp
        Book.cpp
        VolumeStore.h
        VolumeStore.cpp
        OrderConsole.h
        OrderConsole.cpp
        BookConsole.h
        BookConsole.cpp
        Exceptions/Store.Exception.h
        Exceptions/Store.Exception.cpp
        BidStore.h
        BidStore.cpp
        AskStore.h
        AskStore.cpp
        IVolumeMap.h
)

target_include_directories(OrderBook.Core
        PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)